### ISSUE TITLE
CV template

### ISSUE THREAD

**Issue by rafapereirabr** [marvinschmitt/quarto-website-template#1]
Hi Marvin. thanks for sharing this. It's a fantastic resource! I'm wondering how you build the CV. Do you also use a quarto template? Ou an R markdown template?

**Comment by marvinschmitt** [comment]
Hi Rafael,

thanks for the motivating feedback! I built the CV PDF with a slightly customized version of the great **Awesome CV** LaTeX template. You can find the template here: https://github.com/posquit0/Awesome-CV

If you know about any good Quarto tools to build a CV, I would love to hear about them! My dream scenario would be a fully integrated solution where one adds database entries in one single spot (e.g. via JSON or YAML) and use Quarto to automatically deploy the entries to

- an `about-me/` website;
- a `publications/` or `projects/` website;
- a `cv/` website; and
- a CV PDF.

**Comment by rafapereirabr** [comment]
Thanks! I didn't know this Latex template. I've seen the [{vitae}](https://github.com/mitchelloharawild/vitae) package, which offers a few templates in R MarkDown, but I'm looking for a similar solution using Quarto
